services:
  server:
    build:
      context: .
      target: final
    ports:
      - 3000:3000

# Docker image Registry
  registry:
    image: registry:2
    ports:
    - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./registry-data:/data