[gdrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0AQvPyIM-zcLlltNq6xkvleBuYx3Laae59iGD0Sx8kkIVBKE7Os7mk-kJDuUJgJTrTPlPB6SYqgDH5G5j1lGwnvQmxIak3JyzC4rKLTz8die6AQBqSFHXnetDW17UNBs1ZkiJs5hHCF0RsvL2hG0uYGmZRUf4fqgY6SD4b7pzgH8va89r4_sDaJmxUY289iQ2hvAk_b0aCgYKAQESARESFQHGX2MippQVMQSGSjTiHVPMnki0FA0206","token_type":"Bearer","refresh_token":"1//03gw5zkUG7lI3CgYIARAAGAMSNwF-L9IrRlauRoGMRfiOXhc06fGu0EBtmnx-wsrTzQ4i191jgEeSd9vJGk3KpHIOMEO732hurDM","expiry":"2026-06-03T04:14:10.029692514Z","expires_in":3599}
team_drive =
