[gdrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0AQvPyIODZzR-5hSItMyuGR9dVcb7Y_j2pRyMmqKWKaqVCaXuFF92Y5ZLusQxZU12kD9M9O9UuOqSnEhqYUnpZfEvnhgyKUEMZexqa_nydIZG7ih1_r9GGUSqMk9i4p9XLq-egwXZgje_aJnp0yQf52B356rK4vbC-B1FcZMqOlCW-VojUCywU3jOHNuVPlB74l_C284aCgYKAfASARESFQHGX2MiD2IdR-dV798wmaV_VWsItw0206","token_type":"Bearer","refresh_token":"1//03_2wcLOZc6D2CgYIARAAGAMSNwF-L9IrE2iZq6SfPH2oERgu9q_WnzWR51POYnRvhmSDWvslz56SuJsyGRFrdkCs9QElegP5V1I","expiry":"2026-06-03T02:09:58.688376377Z","expires_in":3599}
team_drive =
